-- desc-rich-batch-08.sql
-- Generated 2026-07-06 | scope: RICH | rows: 14
-- STAGED ONLY -- not yet applied. Guarded: is_claimed = false, id must match.
-- Sets description only, per hard rule 4 (no other column touched).
UPDATE public.ranges AS r
SET description = v.description
FROM (VALUES
  ('6afe4757-1d05-4921-b743-d4ed852f2981','Wolf Pack Archers, based in Vernal, Utah, is a USA Archery affiliated club running a full slate of programming for a small-town operation: Junior Olympic Archery Development, an Adult Archery Program, 3D archery, and field archery all under one roof. That breadth means the club serves nearly every kind of archer, from kids on the JOAD pathway to adult target shooters to bowhunters working a 3D course to field archers shooting longer, varied-distance rounds. Vernal sits in a remote corner of northeastern Utah near dinosaur country, and a club offering this much programming likely functions as the area''s main hub for the sport. Contacting the club directly is the way to get current scheduling for each program.'),
  ('4a9869f3-40ab-4543-9c34-5cba8d8ded0f','Roodhouse is a small town in west-central Illinois, and Wolf Run Bowhunters is the local outlet for archers there who shoot 3D. The club carries ASA affiliation, placing it in the competitive 3D archery circuit rather than strictly target or field shooting, and it runs a 3D course for members and visitors to work through. CJ Turner is listed as the contact, a useful starting point for anyone trying to find out about walk-on policies, event dates, or membership. As a volunteer club, expect a grassroots operation shaped by its members rather than posted business hours, so a call ahead is the way to confirm details before making the trip.'),
  ('e41c5c9f-88d0-4231-8878-f36a83ba0829','In Sherman Oaks, tucked into the San Fernando Valley side of Los Angeles, Woodley Park Archers runs as a USA Archery affiliated club with programs built for more than one kind of archer. Its Junior Olympic Archery Development (JOAD) program gives young archers a structured path from fundamentals toward competition, while a separate Adult Archery Program covers members picking up a bow later in life. That two-track setup is worth noting for LA-area archers deciding where to start, since not every affiliated club runs both tiers. Course details and amenities beyond the programs aren''t listed, so confirming schedules and enrollment directly with the club is the next step.'),
  ('8064f939-2fc4-4d40-9111-cbf9d8e553a2','Woodward Archers has operated as an ASA-affiliated archery club in Woodward, in the northwestern Oklahoma panhandle region, putting it within the 3D and bowhunting-oriented side of the sport that ASA represents. The club''s own record lists its affiliation status as expired in 2025, so anyone checking this club out should confirm directly whether that membership has since been renewed rather than assume it''s current. Beyond the affiliation history, no course details, programs, or amenities are listed for this location. Given the status question, a quick call to the club is worth making before planning a visit, both to gauge activity level and ask what''s actually available on-site.'),
  ('50c929cd-f699-417d-8a82-3e2569ef4cb4','Wylie Karate Archery Club, based in Wylie in the Dallas-Fort Worth suburbs, is an interesting hybrid in name as well as structure, pairing archery with a martial arts program under one roof. On the archery side, it holds USA Archery affiliation and runs Field Archery, putting it in the shooting-through-varied-terrain tradition rather than pure indoor target work. That combination of disciplines could appeal to families in the DFW area looking for more than one activity in the same place. No details on lanes, course length, or additional amenities are listed, so confirming class times and how the archery and karate sides are scheduled is best done directly with the club.'),
  ('118b5bcc-7554-46a1-a12a-d11e3e3c324c','X-ten Archery Academy sits in Mountain View, in the heart of Silicon Valley, and runs as a USA Archery affiliated club built around its Junior Olympic Archery Development (JOAD) program. That JOAD pathway is aimed at younger archers working through a structured progression toward competitive shooting, making this academy a natural fit for Bay Area families looking for a serious, affiliated program rather than casual drop-in shooting. No details on adult programming, course type, or facility amenities are listed here, so parents or prospective members should reach out directly to confirm age groups, schedule, and enrollment for the JOAD track.'),
  ('25286725-43d8-4fc6-a8a1-61280ad49eda','In Houston, X10 Academy runs a USA Archery affiliated program that covers more ground than most single-track clubs: Junior Olympic Archery Development (JOAD) for younger archers, a separate Adult Archery Program for grown members, and lessons on top of both. That combination signals an academy built around teaching rather than just providing lane access, useful for Houston-area families or adults who are completely new to a bow and want structured instruction instead of figuring it out alone. Course type, lane count, and other facility details aren''t specified here, so confirming current class schedules and enrollment is worth a direct call before showing up.'),
  ('60928ff5-33a9-4c21-bff0-8ba744d31309','Xcelerated Archery Training, in Poway northeast of San Diego, is a USA Archery affiliated club that spans three program tracks at once: Junior Olympic Archery Development (JOAD) for youth, an Adult Archery Program for grown members, and 3D Archery for those shooting at simulated field targets. Covering youth, adult, and 3D under one affiliated roof is a fairly broad offering compared to single-track clubs, which could make it a useful stop for a San Diego-area family with archers of different ages and interests. No lane count, course length, or additional amenities are listed, so confirming which program fits and current scheduling is best handled with a direct inquiry.'),
  ('6143335c-7df8-44df-87aa-ca9cce8117b8','xspot archery, based in South Attleboro near the Massachusetts-Rhode Island line, combines a few things that don''t always come together at one club: USA Archery affiliation, a JOAD program for younger archers, an on-site pro shop, and lessons. That mix means a newcomer in the South Attleboro area could plausibly get outfitted, taught, and enrolled in a structured youth pathway without needing to visit a separate retailer. No specifics on lane count or course type are given, but the combination of teaching and retail on-site is a genuine convenience worth noting for archers in that corner of southeastern New England looking for a one-stop club.'),
  ('bbe7fcd8-3935-4337-b305-c0028a1a0567','Yarak Archery, based in Pittsboro in central North Carolina''s Chatham County, is an ASA-affiliated 3D club that also runs a pro shop and eight lanes on-site, a fuller setup than most volunteer clubs manage. The ASA affiliation and 3D course point this one toward bowhunters and 3D competitors rather than pure target archers, while the eight lanes and shop suggest there''s also room for regular practice and gear needs without a separate retail trip. Joshua Johnson is listed as the contact for the club. No details on hours or membership cost are given here, so reaching out to Joshua directly is the way to confirm access and current offerings.'),
  ('accd4b85-a9ca-45b5-aa88-ccb4dffbb3fe','Yard Short Archery is a volunteer-run, ASA-affiliated 3D club based in Patton, a small community in southeastern Missouri''s Bollinger County. The ASA tie and 3D format put the focus on foam-animal target shooting at varied, unmarked distances, the format most associated with bowhunting practice rather than indoor target work. Timothy Adams is listed as the contact for anyone wanting to reach the club. As a volunteer operation, expect the range to run on member time and local word of mouth rather than fixed public hours, so a call to Timothy ahead of a visit is the practical way to confirm the course is active and open to guests.'),
  ('6b5930f2-af3b-4e77-8431-fbbf47d42ec1','Youth Shooting Sports Association, based in Bettendorf on Iowa''s Quad Cities side of the Mississippi River, is a USA Archery affiliated club running three programs at once: Junior Olympic Archery Development (JOAD), an Adult Archery Program, and 3D Archery. Despite the youth-focused name, the adult and 3D tracks mean the club isn''t limited to kids'' programming alone, giving Quad Cities-area archers of different ages and interests a single affiliated club to consider. No lane count, course length, or facility amenities are specified for this location, so confirming which program is the right fit and current enrollment details is best done directly with the association.'),
  ('ad3843ed-14df-425a-a407-4171930f9643','Yuba-Sutter Archery Association, based in Marysville at the point where the Yuba and Feather Rivers meet in California''s Central Valley, runs as a USA Archery affiliated club with two program tracks: Junior Olympic Archery Development (JOAD) for younger archers and a separate Adult Archery Program for grown members. That dual setup gives the Marysville-Yuba City area a structured, affiliated option for archers regardless of age, rather than a single youth-only or adult-only track. No details on course type, lane count, or additional amenities are listed for this location, so confirming current schedules and how to enroll in either program is worth a direct call to the association.'),
  ('5988ed09-32c3-4f19-aab9-e5f6191ad0b0','Zimmerman Archery operates in Zimmerman, a town north of the Twin Cities in central Minnesota, and is recorded as a commercial business rather than a club. Its listing traces back to the IBO directory, where it''s noted as a pro shop, tying it to the International Bowhunting Organization''s network of retailers and bowhunting-focused businesses rather than a target-archery or Olympic-style program. That IBO connection suggests a bowhunting and 3D equipment focus more than youth development programming, fitting for Minnesota''s strong hunting culture. No details on lane count, course type, or hours are listed here, so contacting the shop directly is the way to confirm current stock, services, and hours.')
) AS v(id, description)
WHERE r.id = v.id::uuid AND r.is_claimed = false;
